### ISSUE TITLE
plz add a visible version number

### ISSUE THREAD

**Issue by D0NM** [25A0/Quadtastic#15]
I tried the binaries from itch.io some days ago
and got confused.

**Comment by 25A0** [comment]
What exactly caused confusion?
The version number should be visible in the window title.

**Comment by D0NM** [comment]
It is nothing special, actually.

I saw some bugfixes here. Then went to itch.io to dl the new version and got the same old version in the result.

**Comment by 25A0** [comment]
I see :)
Sorry about the confusion. Each time I release a new version on itch.io, I also create a new release here on GitHub. You can find those here: https://github.com/25A0/Quadtastic/releases

But I'll consider to keep the master branch up to date with the released versions, and move active development to a develop branch. This way whatever you see on GitHub should be available on itch.io, too.

I'm planning to release a new version on itch.io once #8 is implemented. But you can always run Quadtastic from source if you want to use the lastest version :)

**Comment by 25A0** [comment]
I thought some more about this, and decided that I will stick to the current workflow; feature/bugfix branches will be merged into `master` directly. I believe that adding a `develop` branch would be redundant, since the changelog already shows which of the changes are released.

In addition to that, by keeping active development on the `master` branch, the time of the latest commit that is shown on GitHub is more accurate.
